feat: connect lobby to backend
UCLA-Creative-Labs/aurgy pull request #15
Opened 2022-03-04 05:45 UTC by thilan-tran

## Screens
<p align="center">
<img width="600" src="https://user-images.githubusercontent.com/44995807/156706521-df6889c4-5549-468f-afdf-7df52dacc52d.png"/>
</p>

## Changes
- load lobby information from backend
- clean up loading screens
- link to each song in Spotify

2022-03-07 20:20 UTC, BryanPan342 requested changes, later dismissed
i think we need to reconnect

2022-03-07 20:20 UTC, BryanPan342 commented on pages/index.tsx
> +      }));
we dont need this anymore!

2022-03-07 20:20 UTC, BryanPan342 commented on pages/index.tsx
> +    setLobbies(lobbies.concat({...lobby, id: data.id}));
```suggestion
    setLobbies(prev => [...prev, {...lobby, id: data.id}]);
```

2022-03-07 20:20 UTC, BryanPan342 commented on pages/index.tsx
> +}
i dont understand why u need id

2022-03-07 20:20 UTC, BryanPan342 commented on pages/lobby.tsx
> +  }
smth tells me this should be part of the app context? like as part of sign out

2022-03-08 16:42 UTC, thilan-tran commented
## Changes
- update to work with API changes
- merge with #11 
- use shaders on home page
- add footer on home page
- set lobby text on a curve with [circletype.labwire.ca](https://circletype.labwire.ca/)
- TODO: change create button to a plus icon

2022-03-20 06:54 UTC, BryanPan342 requested changes, later dismissed
looking a lot more up to date! got a couple of things I would like you to change

2022-03-20 06:54 UTC, BryanPan342 commented on utils/lobby-data.ts
> +  readonly users: ILobbyUser[];
to me, it seems that we can condense some of this using some clever `interfaces`

```ts
export interface ILobbyDataBase {
  readonly id: string;
  readonly name: string;
}

export interface ILobbyUser extends ILobbyBase {}

export interface ILobbySong extends ILobbyBase {
  readonly artists: string[];
  readonly contributors: string[];
}

export interface ILobbyDataBase extends ILobbyBase {
  readonly theme: string;
}

export interface ILobbyData extends ILobbyDataBase {
  reaodnly managerId: string;
  readonly managerName: string;
  readonly songs: ILobbySong[];
  readonly user: ILobbyUser[];
}

```

2022-03-20 06:54 UTC, BryanPan342 commented on styles/lobby.module.scss
> +@use 'LobbyCircle.module' as *;
oh damn.. okay i dont know how i didn't notice this..

preferably only the variables.modules file will be *.. everything else should follow modular CSS..

```ts
@use 'mixins.module' as mixin;
``` 

and I think we can put LobbyCircle variables into the variable CSS file!

2022-03-20 06:54 UTC, BryanPan342 commented on styles/LobbyCircle.module.scss
> +@use 'mixins.module' as *;
```suggestion
@use 'mixins.module' as mixin;
```

2022-03-20 06:54 UTC, BryanPan342 commented on styles/LobbyCircle.module.scss
> +$circle-offset: 4.5vh;
move to variables

2022-03-20 06:54 UTC, BryanPan342 commented on components/LobbyCircle.tsx
> +    }
why isnt this just the size of the element? we have a ref already to it

2022-03-20 06:54 UTC, BryanPan342 commented on components/LobbyCircle.tsx
> +  }, [ref]);
why not just on mount?

2022-03-20 06:54 UTC, BryanPan342 commented on components/LobbyCircle.tsx
> +  return href ? (<NextLink href={href}>{base}</NextLink>) : base;
Let's modify the `Link` component  that i already made to cover this feature too.. maybe like a `isDisabled` prop

2022-03-20 06:54 UTC, BryanPan342 commented on components/Footer.tsx
> +    <div id={styles.navbar}>
erm id?

2022-03-20 06:54 UTC, BryanPan342 commented on pages/index.tsx
> +      <Footer />
smth tells me this should be in the layout

2022-03-20 06:54 UTC, BryanPan342 commented on pages/lobby.tsx
> +                  <Tooltip text="PLAY">
let's remove this tooltip because we aren't planning on playing anytime soon

2022-03-20 06:54 UTC, BryanPan342 commented on pages/lobby.tsx
> +      name => ({name, shape: lobbyData.participantShapes[name] ?? 'pentagon'}),
nit: might be prudent just to keep a map of contributor to the prop values

2022-04-17 02:47 UTC, BryanPan342 commented
@thilan-tran what we could do is just take the repo you have and copy the files directly over

2022-04-27 18:37 UTC, closed without merging