feat: add polgyon animation for lobby names
UCLA-Creative-Labs/aurgy pull request #7
Opened 2021-12-22 06:00 UTC by thilan-tran

## WIP Demo

![polygon3](https://user-images.githubusercontent.com/44995807/147043233-4eee8ecb-93d9-4328-bf26-02da351f7fd1.gif)

2022-01-24 18:02 UTC, thilan-tran commented
@BryanPan342 Not sure how to solve these failing Mergify checks, any ideas? 😶

2022-01-24 23:22 UTC, BryanPan342 commented
> @BryanPan342 Not sure how to solve these failing Mergify checks, any ideas? 😶 

I'll fix it later tonight! I had to fix it on the backend :/

2022-01-25 00:02 UTC, BryanPan342 requested changes, later dismissed
Very sexy! Some stuff that I would like to see changed before I'm ready to merge!

2022-01-25 00:02 UTC, BryanPan342 commented on components/Link.tsx
> +  children: JSX.Element;
```suggestion
  children: React.ReactNode;
```

Allows for the string too I think

2022-01-25 00:02 UTC, BryanPan342 commented on utils/animations.ts
> +function animate(target: HTMLElement, key: string, val: string | number, duration: number, delay = 0): void {
I'm not sure how I feel about this helper function.. I'm not sure if provides much value than using the direct api...

If you want to creat "defaults" maybe it would be better to create a default map to use?

2022-01-25 00:02 UTC, BryanPan342 commented on utils/animations.ts
> +function morphPolygon(target: HTMLElement, shape: Polygon, forwards: boolean, delay = 0): void {
IMO any parameter list that's longer than 3 should be expressed in an `options` or `props` parameter, esp since there seems to be duplicate params across these animation functions

2022-01-25 00:02 UTC, BryanPan342 commented on utils/animations.ts
> +  if (forwards) {
I like ur model up above on L27.. would prefer if the properties were expressed as ternary operations to reduce line count..

I'm not sure if this forwards backwards thing is right but it seems to be working

2022-01-25 00:02 UTC, BryanPan342 commented on components/Navbar.tsx
> +        <Link href='/lobby'>{strikeCurrentPath('/lobby', 'lobbys')}</Link>
Check out `activeClassName` I think that solves this implementation

2022-01-25 23:17 UTC, BryanPan342 requested changes, later dismissed
thoughts on this model for the parameters in the animations file?

2022-01-25 23:17 UTC, BryanPan342 commented on .mergify.yml
>        - status-failure=Semantic Pull Request
remove this!

2022-01-25 23:17 UTC, BryanPan342 commented on components/Link.tsx
> +  // https://github.com/vercel/next.js/tree/canary/examples/active-class-name
o nice i thought this existed.. but this is good too!!

2022-01-25 23:17 UTC, BryanPan342 commented on utils/animations.ts
> +  });
this seems like it can be turned into a function since it gets reused later

2022-01-25 23:17 UTC, BryanPan342 commented on utils/animations.ts
> +): void {
can we have these be options? the parameters have a lot in common and I think the following model will be helpful for the other devs

```ts
interface BaseAnimationOptions {
  readonly target: HTMLElement;
  readonly forwards: boolean;
}

interface MorphPloygonOptions extends BaseAnimationOptions {
  readonly shape: Polygon;
}

interface AnimatePloygonOptions extends MorphPolygonOptions {
  readonly polygonNode: HTMLElement;
}
```

2022-01-27 03:04 UTC, BryanPan342 approved these changes
LGTM

2022-01-27 03:05 UTC, merged